### ISSUE TITLE
Avoid "bigram-ifying" if an input is an array?

### ISSUE THREAD

**Issue by khxu** [words/dice-coefficient#22]
First, thanks for the awesome work on this project!

Second, I didn't see a previous issue on this so thought I'd ask -- would there be interest in detecting whether the inputs to the `diceCoefficient` function have already been "bigram-ified"? I was working on some analysis that involved comparing the Dice coefficients between the strings of two large batches of text files, and refactoring to skip "bigram-ifying" if the input argument was an array significantly sped things up, as I could "bigram-ify" all strings once upfront and that cost would be amortized across all subsequent comparisons.

Happy to submit a PR if that'd help.

**Comment by wooorm** [comment]
Sounds good to me yeah! PR appreciated!

**Comment by wooorm** [comment]
Solved in GH-23.
