### ISSUE TITLE
Slice is always defined

### ISSUE THREAD

**Issue by sdegutis** [words/dice-coefficient#24]
Your line:

```js
    source = value.slice ? value : String(value)
```

is probably not doing what you mean it to?

```js
> "foo".slice
[Function: slice]

> ["foo"].slice
[Function: slice]

> "foo".slice === ["foo"].slice
false
```

**Comment by wooorm** [comment]
where’s that used here?

**Comment by wooorm** [comment]
If you mean https://github.com/words/n-gram/blob/c4def58634cca753057d353ca749d6ecc62e2352/index.js#L40, it’s used to support anything that has slice (arrays, strings, or create-your-own-funky-object), while still casting other values to strings!

**Comment by sdegutis** [comment]
Ok 👍
